package com.journal.employeemanagementdto.service;


import com.journal.employeemanagementdto.dto.EmployeeDTO;
import com.journal.employeemanagementdto.entity.Employee;
import com.journal.employeemanagementdto.repository.EmployeeRepository;
import org.springframework.stereotype.Service;

import java.util.List;
import java.util.stream.Collectors;

@Service
public class EmployeeService {

    private final EmployeeRepository employeeRepository;

    public EmployeeService(EmployeeRepository employeeRepository) {
        this.employeeRepository = employeeRepository;
    }

    //save() is a Spring Data JPA method that persists an entity to the database.
    //✔ SQL generated by Hibernate
    //✔ No manual SQL needed

    public Employee createEmployee(Employee employee) {
        return employeeRepository.save(employee);
    }

    //This method retrieves all Employee entities from the database,
    // converts each entity into an EmployeeDTO using Java Streams,
    // and returns a list of DTOs so that only required fields are exposed to the client.

    public List<EmployeeDTO> getAllEmployees() {
        return employeeRepository.findAll()
                .stream()
                .map(emp -> new EmployeeDTO(emp.getName(), emp.getEmail()))
                .collect(Collectors.toList());
    }


    //id → Which employee to update
    //emp → New data sent by the client
    //Returns → Updated Employee entity

    public Employee updateEmployee(Long id, Employee emp) {
        Employee existing = employeeRepository.findById(id).orElseThrow();
        //existing → entity fetched from DB
        //emp → new data from request
        existing.setName(emp.getName());
        existing.setEmail(emp.getEmail());
        existing.setSalary(emp.getSalary());
        return employeeRepository.save(existing);
    }


    //It deletes an employee record from the database using the given id.
    public void deleteEmployee(Long id) {
        employeeRepository.deleteById(id);
    }
}
