package com.journal.employeemanagementdto.service;


import com.journal.employeemanagementdto.dto.EmployeeDTO;
import com.journal.employeemanagementdto.dto.EmployeeResponseDTO;
import com.journal.employeemanagementdto.entity.Employee;
import com.journal.employeemanagementdto.repository.EmployeeRepository;
import org.springframework.stereotype.Service;

import java.util.List;

@Service
public class EmployeeService {

    private final EmployeeRepository employeeRepository;

    public EmployeeService(EmployeeRepository employeeRepository) {
        this.employeeRepository = employeeRepository;
    }

    //save() is a Spring Data JPA method that persists an entity to the database.
    //✔ SQL generated by Hibernate
    //✔ No manual SQL needed

    public EmployeeResponseDTO createEmployee(EmployeeDTO dto) {
        Employee emp = new Employee();
        emp.setName(dto.getName());
        emp.setEmail(dto.getEmail());
        emp.setSalary(dto.getSalary());

        Employee saved = employeeRepository.save(emp);
        return mapToResponse(saved);
    }

    //This method retrieves all Employee entities from the database,
    // converts each entity into an EmployeeDTO using Java Streams,
    // and returns a list of DTOs so that only required fields are exposed to the client.

    public List<EmployeeResponseDTO> getAllEmployees() {
        return employeeRepository.findAll()
                .stream()
                .map(this::mapToResponse)
                .toList();
    }


    //id → Which employee to update
    //emp → New data sent by the client
    //Returns → Updated Employee entity

    public EmployeeResponseDTO updateEmployee(Long id, EmployeeDTO dto) {
        //Employee existing = employeeRepository.findById(id).orElseThrow();
        Employee existing = employeeRepository.findById(id)
                .orElseThrow(() -> new RuntimeException("Employee not found"));

        //existing → entity fetched from DB
        //emp → new data from request
        existing.setName(dto.getName());
        existing.setEmail(dto.getEmail());
        existing.setSalary(dto.getSalary());

        Employee saved = employeeRepository.save(existing);
        return mapToResponse(saved);
    }


    //It deletes an employee record from the database using the given id.
    public void deleteEmployee(Long id) {
        employeeRepository.deleteById(id);
    }

    //Helper method to map Employee entity to EmployeeResponseDTO
    private EmployeeResponseDTO mapToResponse(Employee emp) {//map entity to DTO
        return new EmployeeResponseDTO(
                //emp.getId(),
                emp.getName(),
                emp.getEmail()
                //emp.getSalary()
        );
    }
}
